# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 19:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 21, 19, 57, 16, 239733, tzinfo=utc)),
        ),
    ]
